// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rvadratjveimrtyavcfq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ2YWRyYXRqdmVpbXJ0eWF2Y2ZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzMDY1NjgsImV4cCI6MjA2MDg4MjU2OH0.1Dsm2f2Bbi4wIlZzmZR07kBRLd3mJ1kR_Il-RFvGiqw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);